### ISSUE TITLE
多状态页面 没有使用案例

### ISSUE THREAD

**Issue by liudao01** [ddnosh/AndroidQuick#2]
多状态页面(loading、empty、error、networkerror)

没有使用案例

**Comment by ddnosh** [comment]
在MainActivity中有个R.id.btn_main_test，目前隐藏了，你把这个设置为visible，然后点击就可以看到具体的使用方法。比如toggleShowEmpty，表示空白页面的显示。其它的还有toggleShowLoading、toggleShowError、toggleNetworkError。另外在Network1Fragment页面也有，只是目前注释掉了，打开即可。

**Comment by liudao01** [comment]
OK 找到了 多谢
